//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Reservation_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room_Usage
    {
        public int Id { get; set; }
        public int Room_Id { get; set; }
        public string Guest_Id { get; set; }
        public double Hours { get; set; }
        public System.DateTime Checkin { get; set; }
        public System.DateTime Date { get; set; }
        public string ApplicationUser_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
